// Weekly newsletter. Triggered on a schedule (Supabase Cron -> this
// function), never by a browser - same pattern as job-alerts-weekly.
//
// Reads the same RSS feed built for Beehiiv (feed.xml, generated by
// export_rss_feed_to_verde_talent.py in the renewable-energy-jobs repo)
// rather than hitting Airtable directly - this function has no Airtable
// credentials, and the feed is already exactly "this week's approved
// stories" in a stable, parseable format.
//
// Sends to everyone in newsletter_subscribers with subscribed=true - this
// list is open-signup (any visitor, not just candidates), kept entirely
// separate from job-alerts-weekly's candidate-only list.
//
// Env vars required (set via `supabase secrets set`):
//   RESEND_API_KEY            - same key the other Edge Functions use
//   SUPABASE_URL              - auto-provided by Supabase
//   SUPABASE_SERVICE_ROLE_KEY - auto-provided by Supabase

import { createClient } from "npm:@supabase/supabase-js@2";
import { Resend } from "npm:resend@4";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const resend = new Resend(Deno.env.get("RESEND_API_KEY")!);
const supabaseAdmin = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);

const SITE_ORIGIN = "https://verdetalent.com";
const FEED_URL = `${SITE_ORIGIN}/feed.xml`;
const MAX_ITEMS = 10;

interface FeedItem {
  title: string;
  link: string;
  description: string;
  category: string | null;
}

// Small hand-rolled RSS parser rather than pulling in an XML/DOM library
// for a Deno edge function - feed.xml's shape is fixed and simple (we
// generate it ourselves), so a few regexes are enough and avoid a new
// dependency for four fields.
function parseFeed(xml: string): FeedItem[] {
  const items: FeedItem[] = [];
  const itemBlocks = xml.match(/<item>[\s\S]*?<\/item>/g) || [];
  for (const block of itemBlocks) {
    const title = block.match(/<title>([\s\S]*?)<\/title>/)?.[1]?.trim();
    const link = block.match(/<link>([\s\S]*?)<\/link>/)?.[1]?.trim();
    const description = block.match(/<description>([\s\S]*?)<\/description>/)?.[1]?.trim() || "";
    const category = block.match(/<category>([\s\S]*?)<\/category>/)?.[1]?.trim() || null;
    if (title && link) items.push({ title, link, description, category });
  }
  return items.slice(0, MAX_ITEMS);
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function buildEmailHtml(items: FeedItem[], unsubscribeToken: string): string {
  const unsubscribeUrl = `${SUPABASE_URL}/functions/v1/unsubscribe-newsletter?token=${unsubscribeToken}`;
  const rows = items.map((item) => `
    <tr>
      <td style="padding:14px 0;border-bottom:1px solid #eee;">
        <a href="${item.link}" style="font-size:15px;font-weight:600;color:#0A0A0A;text-decoration:none;">${escapeHtml(item.title)}</a>
        <div style="font-size:13px;color:#666;margin-top:4px;line-height:1.5;">${item.description}</div>
      </td>
    </tr>`).join("");

  return `
  <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:560px;margin:0 auto;color:#0A0A0A;">
    <p style="font-size:15px;">This week's clean energy news from Verde Talent:</p>
    <table style="width:100%;border-collapse:collapse;">${rows}</table>
    <p style="margin-top:24px;"><a href="${SITE_ORIGIN}/news.html" style="font-size:13px;color:#22E09A;">Read more on Verde Talent →</a></p>
    <p style="margin-top:32px;font-size:11px;color:#999;">
      You're getting this because you subscribed to the Verde Talent newsletter.
      <a href="${unsubscribeUrl}" style="color:#999;">Unsubscribe</a>
    </p>
  </div>`;
}

Deno.serve(async (_req) => {
  try {
    const feedRes = await fetch(FEED_URL);
    if (!feedRes.ok) throw new Error(`Could not fetch feed.xml: ${feedRes.status}`);
    const items = parseFeed(await feedRes.text());

    if (items.length === 0) {
      return new Response(JSON.stringify({ success: true, sent: 0, note: "No feed items this week - nothing sent." }), {
        status: 200,
        headers: { "Content-Type": "application/json" },
      });
    }

    const { data: subscribers, error } = await supabaseAdmin
      .from("newsletter_subscribers")
      .select("id, email, unsubscribe_token")
      .eq("subscribed", true);
    if (error) throw error;

    let sent = 0;
    let failed = 0;

    for (const sub of subscribers || []) {
      const { error: sendError } = await resend.emails.send({
        from: "Verde Talent Newsletter <newsletter@updates.verdetalent.com>",
        to: sub.email,
        subject: "This week in clean energy — Verde Talent",
        html: buildEmailHtml(items, sub.unsubscribe_token),
      });
      if (sendError) {
        console.error(`Send failed for subscriber ${sub.id}:`, sendError);
        failed++;
        continue;
      }
      sent++;
    }

    return new Response(JSON.stringify({ success: true, items_included: items.length, sent, failed }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  } catch (err) {
    console.error(err);
    return new Response(JSON.stringify({ error: String(err) }), { status: 500, headers: { "Content-Type": "application/json" } });
  }
});
